"""init-pack scaffolding — generate a new kb-engine plugin pack skeleton.

`chio-dev init-pack <name>` calls `scaffold_pack(name, dest)` to lay out a
minimal-but-registrable pack on disk. The result is a self-contained
directory `<name>-pack/` containing:

    <name>-pack/
        pyproject.toml             # declares kb_engine.plugins entry point
        README.md                  # 3-paragraph intro
        <name>_pack/__init__.py
        <name>_pack/plugin.py      # stubs for the five protocols
        <name>_pack/schema.py      # uppercase namespace constants
        tests/__init__.py
        tests/test_register.py     # asserts Registry().load_entry_points() finds it

Naming rule: pack names must match `^[a-z][a-z0-9_]*$` — same rule used
by W2-Multitenant for schema namespaces. We refuse to overwrite an
existing target directory; the CLI exits with code 2 in that case.

The generated stubs are registrable as-is: `Registry().load_entry_points()`
discovers and runs `register(registry)` without needing the adopter to
write any code first. Each stub method returns a sensible default
(empty list / pass) so the pack participates in the engine without
producing any output until the adopter fills in the TODO blocks.
"""
from __future__ import annotations

import re
from pathlib import Path

# Pack name validation — same regex W2-Multitenant uses for schema names.
PACK_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


class ScaffoldError(Exception):
    """Raised when a scaffold operation fails (bad name, dir exists, etc)."""


def validate_pack_name(name: str) -> None:
    """Raise ScaffoldError if `name` is not a valid pack name.

    Allowed: lowercase letters, digits, underscore; must start with a
    letter. Mirrors PEP 8 module-name rules and the multitenant schema
    parameterization.
    """
    if not PACK_NAME_RE.match(name):
        raise ScaffoldError(
            f"invalid pack name {name!r}: must match {PACK_NAME_RE.pattern!r} "
            "(lowercase letter start, then letters/digits/underscore)"
        )


def _pyproject_toml(name: str) -> str:
    title = name.capitalize()
    return f'''[project]
name = "{name}-pack"
version = "0.1.0"
description = "{title} schema pack for kb-engine"
requires-python = ">=3.11"
dependencies = [
    "kb-engine",
]

[project.entry-points."kb_engine.plugins"]
{name} = "{name}_pack.plugin"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["{name}_pack"]

[dependency-groups]
dev = [
    "pytest>=8",
]
'''


def _init_py(name: str) -> str:
    return f'''"""{name}-pack — kb-engine plugin scaffold.

Generated by `chio-dev init-pack {name}`. See README.md for the next
decisions to make: which file extensions to ingest, what graph nodes
to project, which frontmatter `type:` values to handle.
"""
__version__ = "0.1.0"
'''


def _plugin_py(name: str) -> str:
    title = name.capitalize()
    upper_name = name.upper()
    return f'''"""Registration of {name}-pack hooks against kb_engine.Registry.

Per the engine ↔ pack boundary: this module imports kb_engine; the engine
never imports this pack (entry-point discovery handles the call back).

The five hook stubs below are intentionally minimal. Each returns a
sensible default so the pack registers cleanly out of the box. Fill in
the TODO blocks one hook at a time as the {title} schema solidifies.
"""
from __future__ import annotations

from typing import Any

from kb_engine import (
    ConstraintSpec,
    DerivedRecord,
    Edge,
    Node,
    ParsedFile,
    Registry,
)

from . import schema


# === SourceIngester ===


def {name}_source_ingester(file_path: str) -> ParsedFile | None:
    """Decide if/how to index a single file.

    Return None to skip; return a ParsedFile to claim it. The first
    plugin that returns non-None wins.

    TODO({name}-pack): pick the file extensions this pack owns
    (e.g. `.{name}`, `.md` under a {name}/ root). Phase 1 can return
    a stub ParsedFile with empty text/symbols and let the engine
    re-read the file; Phase 1.3+ may parse symbols here.
    """
    return None


# === GraphProjector ===


def {name}_graph_projector(parsed: ParsedFile) -> list[Node | Edge]:
    """Emit graph nodes and edges from a parsed file.

    TODO({name}-pack): pick the node labels and edge relationships this
    pack contributes. Use the constants in {name}_pack.schema so labels
    stay namespaced (avoid collisions with other packs in the same
    Neo4j instance).
    """
    return []


# === ToolRegistrar ===


def {name}_tool_registrar(server: object) -> None:
    """Declare MCP tools on the gateway.

    TODO({name}-pack): when the MCP server framework lands, register the
    pack's tools here (e.g. `server.register_tool("kb_{name}_search", ...)`).
    Until then a no-op keeps registration boot clean.
    """
    pass


# === FrontmatterHandler ===


def {name}_frontmatter_handler(
    type: str, frontmatter: dict[str, Any]
) -> list[DerivedRecord]:
    """Interpret a vault note's `type:` value, emit derived records.

    TODO({name}-pack): map each frontmatter type this pack owns to the
    derived store(s) that should receive it (graphiti for episodic,
    neo4j for structural). Emit DerivedRecord(target=..., payload=...)
    objects; the vault-sync daemon is the only writer.
    """
    return []


# === ConstraintProvider ===


def {name}_bootstrap_constraints() -> list[ConstraintSpec]:
    """Declare Neo4j constraints the {name}-pack's labels need.

    TODO({name}-pack): list one ConstraintSpec per label whose `id`
    property must be unique. Example:

        return [
            ConstraintSpec(label=schema.{upper_name}_ARTIFACT,
                           property="id", kind="UNIQUENESS"),
        ]

    The pipeline applies these idempotently at bootstrap time. Empty
    is fine until the first label lands; pack-isolated namespacing
    keeps adopters from colliding even when constraints overlap.
    """
    return []


# === Registry entry point ===


def register(registry: Registry) -> None:
    """Called by `kb_engine.Registry.load_entry_points()`.

    Wired in pyproject.toml under
    `[project.entry-points."kb_engine.plugins"]`.
    """
    registry.register_source_ingester({name}_source_ingester)
    registry.register_graph_projector({name}_graph_projector)
    registry.register_tool_registrar({name}_tool_registrar)
    registry.register_constraint_provider({name}_bootstrap_constraints)
    for type_ in schema.HANDLED_TYPES:
        registry.register_frontmatter_handler(type_, {name}_frontmatter_handler)
'''


def _schema_py(name: str) -> str:
    upper = name.upper()
    title = name.capitalize()
    return f'''"""{name}-pack schema: namespaced labels and edge types.

All node labels are namespaced with the `{title}` prefix to prevent
collisions when multiple packs share a Neo4j instance.

Module constants follow chio-pack's pattern (uppercase identifier,
prefixed with the pack title). Add new constants here, not as inline
strings in plugin.py — keeping the schema in one place is what makes
the pack auditable.
"""
from __future__ import annotations

# === Node labels ===
# TODO({name}-pack): replace with real labels for the {title} domain.
{upper}_ARTIFACT = "{title}Artifact"

ALL_NODE_LABELS = {{
    {upper}_ARTIFACT,
}}


# === Edge relationship vocabulary ===
# TODO({name}-pack): replace with real edge types.
CONTAINS = "CONTAINS"


# === Frontmatter types this pack handles ===
#
# Vault notes whose `type:` matches one of these are routed through
# the FrontmatterHandler in plugin.py. Empty by default — the scaffold
# registers no frontmatter handlers until the adopter declares which
# types belong to {title}.
HANDLED_TYPES: frozenset[str] = frozenset()


def is_{name}_label(label: str) -> bool:
    """True if the label is in this pack's namespace."""
    return label in ALL_NODE_LABELS
'''


def _readme_md(name: str) -> str:
    title = name.capitalize()
    return f'''# {name}-pack

Scaffold generated by `chio-dev init-pack {name}`. This pack registers
{title}-domain hooks against kb-engine's plugin registry — a SourceIngester,
a GraphProjector, a ToolRegistrar, a FrontmatterHandler, and a
ConstraintProvider (per-pack Neo4j constraints). Each hook is a stub
today; the TODO blocks in `{name}_pack/plugin.py` and
`{name}_pack/schema.py` mark the next decisions to make.

To register: install the pack with `pip install -e .` (or `uv pip install -e .`)
into the same environment as kb-engine. Discovery happens via the
`[project.entry-points."kb_engine.plugins"]` declaration in pyproject.toml,
so once installed `Registry().load_entry_points()` picks it up automatically.
The bundled `tests/test_register.py` proves the wire-up — run `pytest` and
all five protocols should appear in the registry.

Eval fixtures for this pack belong under `eval/fixtures/<eval-id>/` once
you have an eval design. See `kb-engine/eval/template/` for the canonical
fixture format (id, failing_test, failure_message, canonical_fix, etc).
Copy `example.yml` from there as a starting point — the same six-field
shape works across every eval category.
'''


def _test_register_py(name: str) -> str:
    return f'''"""Registration smoke test for {name}-pack.

Asserts that:
  - The five protocol hooks register cleanly via `register()`.
  - `Registry().load_entry_points()` discovers this pack via its
    pyproject.toml entry-point declaration.

Run with `uv run pytest` from the pack root after `uv sync`.
"""
from __future__ import annotations

from kb_engine import Registry

from {name}_pack import plugin


def test_register_populates_all_hook_types():
    """Direct-registration path — proves all five hooks wire in."""
    r = Registry()
    plugin.register(r)
    assert len(r.source_ingesters) == 1
    assert len(r.graph_projectors) == 1
    assert len(r.tool_registrars) == 1
    assert len(r.constraint_providers) == 1
    # Frontmatter handlers may be empty by default (HANDLED_TYPES is empty
    # in the scaffold). The dict structure is what we verify here; once
    # the adopter populates HANDLED_TYPES, those types get registered.
    assert isinstance(r.frontmatter_handlers, dict)


def test_entry_point_loadable_via_registry():
    """Entry-point discovery — proves the pyproject.toml declaration works.

    This is the test an adopter runs to confirm `pip install -e .`
    actually wired the pack into kb-engine.
    """
    r = Registry()
    n = r.load_entry_points()
    assert n >= 1, "expected at least {name}-pack's entry point to load"
    assert len(r.source_ingesters) >= 1
    assert len(r.graph_projectors) >= 1
    assert len(r.tool_registrars) >= 1
    assert len(r.constraint_providers) >= 1
'''


def _tests_init_py() -> str:
    return ""


def scaffold_pack(name: str, dest: Path) -> Path:
    """Lay out `<name>-pack/` under `dest`. Returns the created directory.

    Refuses to overwrite. Validates the name. Raises ScaffoldError on
    any failure; the CLI surfaces this as exit code 2.
    """
    validate_pack_name(name)
    dest = dest.resolve()
    pack_dir = dest / f"{name}-pack"
    if pack_dir.exists():
        raise ScaffoldError(
            f"refusing to overwrite existing directory: {pack_dir}"
        )
    pkg_dir = pack_dir / f"{name}_pack"
    tests_dir = pack_dir / "tests"
    pack_dir.mkdir(parents=True)
    pkg_dir.mkdir()
    tests_dir.mkdir()

    files: dict[Path, str] = {
        pack_dir / "pyproject.toml": _pyproject_toml(name),
        pack_dir / "README.md": _readme_md(name),
        pkg_dir / "__init__.py": _init_py(name),
        pkg_dir / "plugin.py": _plugin_py(name),
        pkg_dir / "schema.py": _schema_py(name),
        tests_dir / "__init__.py": _tests_init_py(),
        tests_dir / "test_register.py": _test_register_py(name),
    }
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
    return pack_dir
